server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${{ secrets.RDS_URL }}
    username: ${{ secrets.RDS_USERNAME }}
    password: ${{ secrets.RDS_PASSWORD }}
  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

config:
  nickname-change-days: 14
