server:
  port: 8000
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/galma?characterEncoding=UTF-8
    username: root
    password: qpzja528
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:classpath:env.properties

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

config:
  nickname-change-days: 0

api:
  weather:
    uri: ${env.api.uri}
    key: ${env.api.key}